# Aula 1 -----------------------

Crie dois projetos no seu computador. Alterne entre eles usando o seletor do
RStudio. Teste como funcionam os caminhos absolutos e relativos dentro dos
projetos (dica: abra um parêntese no RStudio e aperte TAB para ver como ele nos
ajuda a escrever caminhos relativos).

# Aula 2 -----------------------

Resolva os exercícios dos capítulos 08, 19 e 21 do _R for Data Science (2e)_:

- Data import: https://r4ds.hadley.nz/data-import.html

- Missing values: https://r4ds.hadley.nz/missing-values.html

- Spreadsheets: https://r4ds.hadley.nz/spreadsheets.html

# Aula 3 -----------------------

Resolva os exercícios dos capítulos 22 e 20 do _R for Data Science (2e)_:

- Databases: https://r4ds.hadley.nz/databases.html

- Joins: https://r4ds.hadley.nz/joins.html

# Aula 4 -----------------------

Crie no GitHub um repositório exemplo e teste todos os comandos Git que
aprendemos na aula. Para simular um `pull` efetivo, adicione um arquivo chamado
README ao seu repo usando a interface do próprio GitHub (com o botão **Add a
README**).

# Aula 5 -----------------------

Crie um pacote e suba ele para o GitHub como ensinado em aula. Transforme o
código abaixo em uma função no pacote, faça com que ele passe no `check()` e
adicione documentação para explicar o que a função faz.

```r
library(tidyverse)

ano <- 2018

"https://git.io/JOqUN" |>
  read_csv2() |>
  group_by(temporada) |>
  filter(quem_ganhou != "Empate", temporada %in% ano) |>
  count(quem_ganhou, sort = TRUE, name = "n_vitorias") |>
  filter(n_vitorias == max(n_vitorias)) |>
  arrange(temporada)
```

# Aula 6 -----------------------
