# TCC --------------------------

O objetivo deste TCC é bastante simples: criar um pacote que passe sem nenhum
erro no `devtools::check()`. O seu pacote deve conter pelo menos duas funções
devidamente documentadas e testes que verifiquem a corretude delas. O pacote não
precisa ter um tema, mas as funções precisam realizar alguma tarefa minimamente
útil.

Quanto mais do curso você utilizar no seu pacote, melhor. Alguns exemplos de
adicionais que podem ser interessantes:

- Um banco de dados DuckDB na pasta `data-raw/` cujas tabelas precisam ser
importadas seguindo os princípios de faxina da aula 02.

- Um script de importação na pasta `data-raw/` que cruze tabelas brutas usando
as funções descritas na aula 03.

- Um repositório no GitHub contendo o pacote e todo o histórico de alterações
como descrito na aula 04.

- Um site gerado com pkgdown e atualizado via GitHub Actions da maneira
especificada na aula 06.

O TCC pode ser entregue na forma de um arquivo compactado (`.zip` ou `.tar`) ou,
preferencialmente, de um link para o repositório no GitHub.
